exports.toLabTestPOST = (dto) => ({
  lab_test_name: dto.labTestName,
  lab_test_code: dto.labTestCode,
  cpt_code: dto.cptCode,
  lab_test_method_IDR: dto.labTestMethodIDR,
  lab_test_unit: dto.labTestUnit,
  is_multi_column: dto.isMultiColumn,
  field_type: dto.fieldType,
  from_range: dto.fromRange,
  to_range: dto.toRange,
  is_calculated: dto.isCalculated,
  is_active:dto.isActive,
  formula: dto.Formula,
  calculation_test_IDR: dto.calculationTestIDR,
  remark: dto.Remark,
  used_for_calculation: dto.usedForCalculation,
  detail_type: dto.detailType,
  hospital_IDR: dto.hospitalIDR,
  hospital_group_IDR: dto.hospitalGroupIDR,
  created_by: dto.createdBy,
  //created_at: dto.createdAt,
  updated_by: dto.updatedBy,
 //updated_at: dto.updatedAt,
});

exports.toLabTestEntity = (dto) => ({
  labTestId: dto.lab_test_id,
  labTestName: dto.lab_test_name,
  labTestCode: dto.lab_test_code,
  cptCode: dto.cpt_code,
  labTestMethodIDR: dto.lab_test_method_IDR,
  labTestUnit: dto.lab_test_unit,
  isMultiColumn: dto.is_multi_column,
  fieldType: dto.field_type,
  fromRange: dto.from_range,
  toRange: dto.to_range,
  isCalculated: dto.is_calculated,
  isActive:dto.is_active,
  Formula: dto.formula,
  calculationTestIDR: dto.calculation_test_IDR,
  Remark: dto.remark,
  usedForCalculation: dto.used_for_calculation,
  detailType:dto.detail_type,
  hospitalIDR: dto.hospital_IDR,
  hospitalGroupIDR: dto.hospital_group_IDR,
  // createdBy: dto.created_by,
  // createdAt: dto.created_at,
  // updatedBy: dto.updated_by,
  // updatedAt: dto.updated_at,
});
