exports.serviceType = [
    { value: 0, label: "Select" },
    { value: 1, label: "General Services" },
    { value: 2, label: "Consultation" },
    { value: 3, label: "Visit Charge" },
    { value: 4, label: "Pathalogy" },
    { value: 5, label: "Radiology" },
    { value: 6, label: "Medical Procedure" },
    { value: 7, label: "OT - Surgery" },
    { value: 8, label: "Blood Bank" },
    { value: 9, label: "Bed Charge" },
    { value: 10, label: "Amenity Service" },
    { value: 11, label: "Registration" },
    { value: 12, label: "Indoor Admission" },
    { value: 13, label: "Cross Reference" },
    { value: 14, label: "Ambulance Service" },
    { value: 15, label: "Medico Legal Service" },
    { value: 16, label: "Biomedical Service" },
    { value: 17, label: "Nursing Charge" },
    { value: 18, label: "Operational  Charge" },
    { value: 19, label: "Anesthesia Charge" },
    { value: 20, label: "Equipment Charge" },
];
